export const mock = {
  books: [
    {
      id: "1",
      title: "The Crystal Cavern",
      author: { id: "a1", name: "Eleanor Silverwood" },
      description: "Deep beneath the Misty Mountains lies a cavern of enchanted crystals that hold the power to reveal one's true destiny. When young apprentice mage Lyra discovers an ancient map, she embarks on a perilous journey through magical landscapes.",
      coverUrl: "https://images.pexels.com/photos/2693212/pexels-photo-2693212.png",
      audioUrl: "https://samples-files.com/samples/Audio/mp3/sample-file-4.mp3",
      duration: 18432,
      genre: ["Fantasy", "Adventure"],
      rating: 4.7,
      releaseDate: "2023-07-15"
    },
    {
      id: "2",
      title: "Whispers of the Ancient Ones",
      author: { id: "a2", name: "Thaddeus Nightshade" },
      description: "In the sleepy village of Ravenbrook, the whispers began at midnight. Ancient voices calling from the forest, promising secrets of forgotten magic. But answering their call may awaken something that should remain dormant.",
      coverUrl: "https://images.pexels.com/photos/4245826/pexels-photo-4245826.jpeg",
      audioUrl: "https://samples-files.com/samples/Audio/mp3/sample-file-3.mp3",
      duration: 22186,
      genre: ["Horror", "Fantasy"],
      rating: 4.3,
      releaseDate: "2023-09-21"
    },
    {
      id: "3",
      title: "The Astral Chronicler",
      author: { id: "a3", name: "Zephyr Starborn" },
      description: "When astronomer Elara discovers a journal that records events before they happen, she becomes entangled in a cosmic mystery. The stars themselves seem to be writing through her, warning of a celestial alignment that could either elevate humanity or destroy it.",
      coverUrl: "https://images.pexels.com/photos/1274260/pexels-photo-1274260.jpeg",
      audioUrl: "https://samples-files.com/samples/Audio/mp3/sample-file-2.mp3",
      duration: 19845,
      genre: ["Science Fiction", "Mystery"],
      rating: 4.9,
      releaseDate: "2023-03-18"
    },
    {
      id: "4",
      title: "Dragon's Ember",
      author: { id: "a4", name: "Magnus Firefist" },
      description: "The last dragon rider must navigate a world torn by war and prejudice. With his emerald dragon Seraphina, young Kael journeys to reunite the scattered dragon clans before the Empire's dragon hunters find them first.",
      coverUrl: "https://images.pexels.com/photos/4065150/pexels-photo-4065150.jpeg",
      audioUrl: "https://samples-files.com/samples/Audio/mp3/sample-file-1.mp3",
      duration: 23452,
      genre: ["Fantasy", "Action"],
      rating: 4.6,
      releaseDate: "2022-11-30"
    },
    {
      id: "5",
      title: "Echoes of Eternity",
      author: { id: "a5", name: "Lyra Dawnlight" },
      description: "When time begins to fold upon itself, memories of futures not yet lived start appearing in dreams. Historian Aria must decipher these temporal echoes to prevent the collapse of reality itself.",
      coverUrl: "https://images.pexels.com/photos/6498303/pexels-photo-6498303.jpeg",
      audioUrl: "https://samples-files.com/samples/Audio/mp3/sample-file-5.mp3",
      duration: 17623,
      genre: ["Science Fiction", "Philosophy"],
      rating: 4.4,
      releaseDate: "2023-01-09"
    },
    {
      id: "6",
      title: "The Enchanted Grimoire",
      author: { id: "a1", name: "Eleanor Silverwood" },
      description: "A forgotten spellbook chooses a most unlikely apprentice - a kitchen maid with no magical lineage. But as Briar Rose learns to harness her unexpected gifts, she discovers her connection to an ancient magical bloodline thought extinct.",
      coverUrl: "https://images.pexels.com/photos/3646172/pexels-photo-3646172.jpeg",
      audioUrl: "https://samples-files.com/samples/Audio/mp3/sample-file-4.mp3",
      duration: 21378,
      genre: ["Fantasy", "Coming of Age"],
      rating: 4.7,
      releaseDate: "2022-08-23"
    },
    {
      id: "7",
      title: "Shadow of the Phoenix",
      author: { id: "a6", name: "Orion Blackwood" },
      description: "Every hundred years, the Phoenix King must sacrifice his memories to be reborn. But this time, the king's shadow has gained sentience and seeks to usurp the throne, threatening to plunge the realm into eternal darkness.",
      coverUrl: "https://images.pexels.com/photos/6758048/pexels-photo-6758048.jpeg",
      audioUrl: "https://samples-files.com/samples/Audio/mp3/sample-file-3.mp3",
      duration: 20152,
      genre: ["Dark Fantasy", "Epic"],
      rating: 4.8,
      releaseDate: "2023-02-14"
    },
    {
      id: "8",
      title: "Moonlight Serenade",
      author: { id: "a7", name: "Isabella Nightingale" },
      description: "In a world where music is magic, violinist Clara discovers that her melodies can open doorways between realms. When her brother is lured away by an otherworldly song, she must venture into the faerie courts to bring him home.",
      coverUrl: "https://images.pexels.com/photos/4065624/pexels-photo-4065624.jpeg",
      audioUrl: "https://samples-files.com/samples/Audio/mp3/sample-file-2.mp3",
      duration: 16982,
      genre: ["Fantasy", "Musical"],
      rating: 4.5,
      releaseDate: "2023-05-30"
    },
    {
      id: "9",
      title: "The Celestial Cartographer",
      author: { id: "a8", name: "Professor Artemis Starweaver" },
      description: "A disgraced royal cartographer discovers that the stars are shifting out of their ancient patterns. His quest to redraw the celestial maps leads to the revelation that the universe itself may be a conscious entity trying to communicate.",
      coverUrl: "https://images.pexels.com/photos/5186869/pexels-photo-5186869.jpeg",
      audioUrl: "https://samples-files.com/samples/Audio/mp3/sample-file-1.mp3",
      duration: 24735,
      genre: ["Science Fiction", "Philosophical"],
      rating: 4.9,
      releaseDate: "2022-12-12"
    },
    {
      id: "10",
      title: "The Alchemist's Apprentice",
      author: { id: "a9", name: "Cornelius Copperfield" },
      description: "Young Thomas becomes apprenticed to the kingdom's master alchemist, only to discover his mentor is searching for the forbidden Elixir of Immortality. As royal agents close in, Thomas must decide whether to help complete the dangerous formula or destroy it forever.",
      coverUrl: "https://images.pexels.com/photos/6498287/pexels-photo-6498287.jpeg",
      audioUrl: "https://samples-files.com/samples/Audio/mp3/sample-file-5.mp3",
      duration: 19267,
      genre: ["Historical Fantasy", "Adventure"],
      rating: 4.6,
      releaseDate: "2023-04-07"
    },
    {
      id: "11",
      title: "Chronicles of the Fae Folk",
      author: { id: "a10", name: "Willow Whispersong" },
      description: "A collection of interconnected stories about the hidden fae folk living at the edges of human society, revealing their magic, mischief, and unexpected moments of profound connection with unsuspecting humans.",
      coverUrl: "https://images.pexels.com/photos/2832043/pexels-photo-2832043.jpeg",
      audioUrl: "https://samples-files.com/samples/Audio/mp3/sample-file-4.mp3",
      duration: 18569,
      genre: ["Fantasy", "Short Stories"],
      rating: 4.4,
      releaseDate: "2023-06-21"
    },
    {
      id: "12",
      title: "The Quantum Paradox",
      author: { id: "a11", name: "Dr. Quantum Enigma" },
      description: "When physicist Dr. Maya Sharma's quantum experiment creates a rift in reality, she finds herself able to communicate with her parallel selves across multiple timelines. Together, they must solve a mystery that threatens the entire multiverse.",
      coverUrl: "https://images.pexels.com/photos/4064432/pexels-photo-4064432.jpeg",
      audioUrl: "https://samples-files.com/samples/Audio/mp3/sample-file-3.mp3",
      duration: 22780,
      genre: ["Science Fiction", "Thriller"],
      rating: 4.7,
      releaseDate: "2023-08-03"
    },
    {
      id: "13",
      title: "The Last Spellweaver",
      author: { id: "a12", name: "Raven Moonshadow" },
      description: "In a world where magic is dying, the last spellweaver must journey across the realm to rekindle the ancient sources of power. But as she discovers the true cost of magic's return, she questions whether some powers are better left forgotten.",
      coverUrl: "https://images.pexels.com/photos/3075993/pexels-photo-3075993.jpeg",
      audioUrl: "https://samples-files.com/samples/Audio/mp3/sample-file-4.mp3",
      duration: 25140,
      genre: ["Fantasy", "Epic"],
      rating: 4.8,
      releaseDate: "2023-09-15"
    },
    {
      id: "14",
      title: "Neon Dreamwalker",
      author: { id: "a13", name: "Cyber Shadow" },
      description: "In Neo Tokyo 2085, a dreamwalker discovers she can hack people's neural implants through their dreams. As corporate conspiracies unfold, she must navigate both the digital and dream worlds to expose the truth behind a series of mysterious comas.",
      coverUrl: "https://images.pexels.com/photos/3052361/pexels-photo-3052361.jpeg",
      audioUrl: "https://samples-files.com/samples/Audio/mp3/sample-file-2.mp3",
      duration: 23180,
      genre: ["Cyberpunk", "Science Fiction"],
      rating: 4.6,
      releaseDate: "2023-10-01"
    },
    {
      id: "15",
      title: "The Time Merchant",
      author: { id: "a14", name: "Chronos Vale" },
      description: "A mysterious shop appears in different eras, run by an enigmatic merchant who trades in moments of time. But when a customer tries to change a pivotal moment in history, the fabric of time itself begins to unravel.",
      coverUrl: "https://images.pexels.com/photos/1428277/pexels-photo-1428277.jpeg",
      audioUrl: "https://samples-files.com/samples/Audio/mp3/sample-file-5.mp3",
      duration: 20750,
      genre: ["Science Fiction", "Mystery"],
      rating: 4.9,
      releaseDate: "2023-07-22"
    },
    {
      id: "16",
      title: "Whispers of the Deep",
      author: { id: "a15", name: "Marina Tideweaver" },
      description: "A marine biologist discovers an ancient underwater civilization communicating through bioluminescent patterns. As she learns their language, she uncovers a warning about a catastrophic event that could affect both their worlds.",
      coverUrl: "https://images.pexels.com/photos/3894157/pexels-photo-3894157.jpeg",
      audioUrl: "https://samples-files.com/samples/Audio/mp3/sample-file-1.mp3",
      duration: 21890,
      genre: ["Science Fiction", "Environmental"],
      rating: 4.7,
      releaseDate: "2023-08-30"
    },
    {
      id: "17",
      title: "The Witch's Grimoire",
      author: { id: "a16", name: "Sage Moonweaver" },
      description: "A modern witch inherits her grandmother's mysterious grimoire, only to find that each spell she casts has unintended consequences that ripple through time. She must master the book's magic to prevent a disaster centuries in the making.",
      coverUrl: "https://images.pexels.com/photos/5245865/pexels-photo-5245865.jpeg",
      audioUrl: "https://samples-files.com/samples/Audio/mp3/sample-file-3.mp3",
      duration: 19460,
      genre: ["Urban Fantasy", "Magical Realism"],
      rating: 4.5,
      releaseDate: "2023-09-05"
    },
    {
      id: "18",
      title: "The Memory Collector",
      author: { id: "a17", name: "Echo Remembrance" },
      description: "In a world where memories can be extracted and sold, a memory collector stumbles upon a memory so dangerous it could reshape society. Now hunted by shadowy organizations, she must decide whether to erase it or expose the truth.",
      coverUrl: "https://images.pexels.com/photos/3075665/pexels-photo-3075665.jpeg",
      audioUrl: "https://samples-files.com/samples/Audio/mp3/sample-file-4.mp3",
      duration: 24180,
      genre: ["Science Fiction", "Thriller"],
      rating: 4.8,
      releaseDate: "2023-10-12"
    },
    {
      id: "19",
      title: "The Starborn Legacy",
      author: { id: "a18", name: "Nova Celestia" },
      description: "A young woman discovers she's the last descendant of an ancient race of starborn beings. As she learns to harness her cosmic powers, she must prevent an interdimensional war that threatens to destroy both her ancestral and adopted homes.",
      coverUrl: "https://images.pexels.com/photos/1274260/pexels-photo-1274260.jpeg",
      audioUrl: "https://samples-files.com/samples/Audio/mp3/sample-file-2.mp3",
      duration: 26340,
      genre: ["Space Opera", "Fantasy"],
      rating: 4.9,
      releaseDate: "2023-11-01"
    },
    {
      id: "20",
      title: "The Clockwork Revolution",
      author: { id: "a19", name: "Gear Winchester" },
      description: "In an alternate Victorian London powered by steam and magic, a young inventor creates a device that can predict the future through mechanical divination. Her invention sparks a revolution that threatens to overthrow the magical aristocracy.",
      coverUrl: "https://images.pexels.com/photos/3990359/pexels-photo-3990359.jpeg",
      audioUrl: "https://samples-files.com/samples/Audio/mp3/sample-file-5.mp3",
      duration: 22960,
      genre: ["Steampunk", "Historical Fantasy"],
      rating: 4.7,
      releaseDate: "2023-11-15"
    }
  ]
};